service:
  port: 8080

spring:
  applications:
    name: user-center
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_center?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root@123

# Mybatis-Plus扫描路径
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml